[canonical-tests]

# slices of one from one
# this test may not be in the suite but has not been intentionally rejected
# "7ae7a46a-d992-4c2a-9c15-a112d125ebad" = false

# slices of one from two
# this test may not be in the suite but has not been intentionally rejected
# "3143b71d-f6a5-4221-aeae-619f906244d2" = false

# slices of two
# this test may not be in the suite but has not been intentionally rejected
# "dbb68ff5-76c5-4ccd-895a-93dbec6d5805" = false

# slices of two overlap
# this test may not be in the suite but has not been intentionally rejected
# "19bbea47-c987-4e11-a7d1-e103442adf86" = false

# slices can include duplicates
# this test may not be in the suite but has not been intentionally rejected
# "8e17148d-ba0a-4007-a07f-d7f87015d84c" = false

# slices of a long series
# this test may not be in the suite but has not been intentionally rejected
# "bd5b085e-f612-4f81-97a8-6314258278b0" = false

# slice length is too large
# this test may not be in the suite but has not been intentionally rejected
# "6d235d85-46cf-4fae-9955-14b6efef27cd" = false

# slice length cannot be zero
# this test may not be in the suite but has not been intentionally rejected
# "d34004ad-8765-4c09-8ba1-ada8ce776806" = false

# slice length cannot be negative
# this test may not be in the suite but has not been intentionally rejected
# "10ab822d-8410-470a-a85d-23fbeb549e54" = false

# empty series is invalid
# this test may not be in the suite but has not been intentionally rejected
# "c7ed0812-0e4b-4bf3-99c4-28cbbfc246a2" = false
