[canonical-tests]

# Only a single book
# this test may not be in the suite but has not been intentionally rejected
# "17146bd5-2e80-4557-ab4c-05632b6b0d01" = false

# Two of the same book
# this test may not be in the suite but has not been intentionally rejected
# "cc2de9ac-ff2a-4efd-b7c7-bfe0f43271ce" = false

# Empty basket
# this test may not be in the suite but has not been intentionally rejected
# "5a86eac0-45d2-46aa-bbf0-266b94393a1a" = false

# Two different books
# this test may not be in the suite but has not been intentionally rejected
# "158bd19a-3db4-4468-ae85-e0638a688990" = false

# Three different books
# this test may not be in the suite but has not been intentionally rejected
# "f3833f6b-9332-4a1f-ad98-6c3f8e30e163" = false

# Four different books
# this test may not be in the suite but has not been intentionally rejected
# "1951a1db-2fb6-4cd1-a69a-f691b6dd30a2" = false

# Five different books
# this test may not be in the suite but has not been intentionally rejected
# "d70f6682-3019-4c3f-aede-83c6a8c647a3" = false

# Two groups of four is cheaper than group of five plus group of three
# this test may not be in the suite but has not been intentionally rejected
# "78cacb57-911a-45f1-be52-2a5bd428c634" = false

# Two groups of four is cheaper than groups of five and three
# this test may not be in the suite but has not been intentionally rejected
# "f808b5a4-e01f-4c0d-881f-f7b90d9739da" = false

# Group of four plus group of two is cheaper than two groups of three
# this test may not be in the suite but has not been intentionally rejected
# "fe96401c-5268-4be2-9d9e-19b76478007c" = false

# Two each of first 4 books and 1 copy each of rest
# this test may not be in the suite but has not been intentionally rejected
# "68ea9b78-10ad-420e-a766-836a501d3633" = false

# Two copies of each book
# this test may not be in the suite but has not been intentionally rejected
# "c0a779d5-a40c-47ae-9828-a340e936b866" = false

# Three copies of first book and 2 each of remaining
# this test may not be in the suite but has not been intentionally rejected
# "18fd86fe-08f1-4b68-969b-392b8af20513" = false

# Three each of first 2 books and 2 each of remaining books
# this test may not be in the suite but has not been intentionally rejected
# "0b19a24d-e4cf-4ec8-9db2-8899a41af0da" = false

# Four groups of four are cheaper than two groups each of five and three
# this test may not be in the suite but has not been intentionally rejected
# "bb376344-4fb2-49ab-ab85-e38d8354a58d" = false
