[canonical-tests]

# should be able to score a game with all zeros
"656ae006-25c2-438c-a549-f338e7ec7441" = true

# should be able to score a game with no strikes or spares
"f85dcc56-cd6b-4875-81b3-e50921e3597b" = true

# a spare followed by zeros is worth ten points
"d1f56305-3ac2-4fe0-8645-0b37e3073e20" = true

# points scored in the roll after a spare are counted twice
"0b8c8bb7-764a-4287-801a-f9e9012f8be4" = true

# consecutive spares each get a one roll bonus
"4d54d502-1565-4691-84cd-f29a09c65bea" = true

# a spare in the last frame gets a one roll bonus that is counted once
"e5c9cf3d-abbe-4b74-ad48-34051b2b08c0" = true

# a strike earns ten points in a frame with a single roll
"75269642-2b34-4b72-95a4-9be28ab16902" = true

# points scored in the two rolls after a strike are counted twice as a bonus
"037f978c-5d01-4e49-bdeb-9e20a2e6f9a6" = true

# consecutive strikes each get the two roll bonus
"1635e82b-14ec-4cd1-bce4-4ea14bd13a49" = true

# a strike in the last frame gets a two roll bonus that is counted once
"e483e8b6-cb4b-4959-b310-e3982030d766" = true

# rolling a spare with the two roll bonus does not get a bonus roll
"9d5c87db-84bc-4e01-8e95-53350c8af1f8" = true

# strikes with the two roll bonus do not get bonus rolls
"576faac1-7cff-4029-ad72-c16bcada79b5" = true

# a strike with the one roll bonus after a spare in the last frame does not get a bonus
"72e24404-b6c6-46af-b188-875514c0377b" = true

# all strikes is a perfect game
"62ee4c72-8ee8-4250-b794-234f1fec17b1" = true

# rolls cannot score negative points
"1245216b-19c6-422c-b34b-6e4012d7459f" = true

# a roll cannot score more than 10 points
"5fcbd206-782c-4faa-8f3a-be5c538ba841" = true

# two rolls in a frame cannot score more than 10 points
"fb023c31-d842-422d-ad7e-79ce1db23c21" = true

# bonus roll after a strike in the last frame cannot score more than 10 points
"6082d689-d677-4214-80d7-99940189381b" = true

# two bonus rolls after a strike in the last frame cannot score more than 10 points
"e9565fe6-510a-4675-ba6b-733a56767a45" = true

# two bonus rolls after a strike in the last frame can score more than 10 points if one is a strike
"2f6acf99-448e-4282-8103-0b9c7df99c3d" = true

# the second bonus rolls after a strike in the last frame cannot be a strike if the first one is not a strike
"6380495a-8bc4-4cdb-a59f-5f0212dbed01" = true

# second bonus roll after a strike in the last frame cannot score more than 10 points
"2b2976ea-446c-47a3-9817-42777f09fe7e" = true

# an unstarted game cannot be scored
"29220245-ac8d-463d-bc19-98a94cfada8a" = true

# an incomplete game cannot be scored
"4473dc5d-1f86-486f-bf79-426a52ddc955" = true

# cannot roll if game already has ten frames
"2ccb8980-1b37-4988-b7d1-e5701c317df3" = true

# bonus rolls for a strike in the last frame must be rolled before score can be calculated
"4864f09b-9df3-4b65-9924-c595ed236f1b" = true

# both bonus rolls for a strike in the last frame must be rolled before score can be calculated
"537f4e37-4b51-4d1c-97e2-986eb37b2ac1" = true

# bonus roll for a spare in the last frame must be rolled before score can be calculated
"8134e8c1-4201-4197-bf9f-1431afcde4b9" = true

# cannot roll after bonus roll for spare
"9d4a9a55-134a-4bad-bae8-3babf84bd570" = true

# cannot roll after bonus rolls for strike
"d3e02652-a799-4ae3-b53b-68582cc604be" = true
