[canonical-tests]





# consecutive spares each get a one roll bonus
"4d54d502-1565-4691-84cd-f29a09c65bea" = true


# a strike earns ten points in a frame with a single roll
"75269642-2b34-4b72-95a4-9be28ab16902" = true

# points scored in the two rolls after a strike are counted twice as a bonus
"037f978c-5d01-4e49-bdeb-9e20a2e6f9a6" = true

# consecutive strikes each get the two roll bonus
"1635e82b-14ec-4cd1-bce4-4ea14bd13a49" = true




# a strike with the one roll bonus after a spare in the last frame does not get a bonus
"72e24404-b6c6-46af-b188-875514c0377b" = true
















# cannot roll after bonus roll for spare
"9d4a9a55-134a-4bad-bae8-3babf84bd570" = true

