[canonical-tests]

# finds the smallest palindrome from single digit factors
# this test may not be in the suite but has not been intentionally rejected
# "5cff78fe-cf02-459d-85c2-ce584679f887" = false

# finds the largest palindrome from single digit factors
# this test may not be in the suite but has not been intentionally rejected
# "0853f82c-5fc4-44ae-be38-fadb2cced92d" = false

# find the smallest palindrome from double digit factors
# this test may not be in the suite but has not been intentionally rejected
# "66c3b496-bdec-4103-9129-3fcb5a9063e1" = false

# find the largest palindrome from double digit factors
# this test may not be in the suite but has not been intentionally rejected
# "a10682ae-530a-4e56-b89d-69664feafe53" = false

# find smallest palindrome from triple digit factors
# this test may not be in the suite but has not been intentionally rejected
# "cecb5a35-46d1-4666-9719-fa2c3af7499d" = false

# find the largest palindrome from triple digit factors
# this test may not be in the suite but has not been intentionally rejected
# "edab43e1-c35f-4ea3-8c55-2f31dddd92e5" = false

# find smallest palindrome from four digit factors
# this test may not be in the suite but has not been intentionally rejected
# "4f802b5a-9d74-4026-a70f-b53ff9234e4e" = false

# find the largest palindrome from four digit factors
# this test may not be in the suite but has not been intentionally rejected
# "787525e0-a5f9-40f3-8cb2-23b52cf5d0be" = false

# empty result for smallest if no palindrome in the range
# this test may not be in the suite but has not been intentionally rejected
# "58fb1d63-fddb-4409-ab84-a7a8e58d9ea0" = false

# empty result for largest if no palindrome in the range
# this test may not be in the suite but has not been intentionally rejected
# "9de9e9da-f1d9-49a5-8bfc-3d322efbdd02" = false

# error result for smallest if min is more than max
# this test may not be in the suite but has not been intentionally rejected
# "12e73aac-d7ee-4877-b8aa-2aa3dcdb9f8a" = false

# error result for largest if min is more than max
# this test may not be in the suite but has not been intentionally rejected
# "eeeb5bff-3f47-4b1e-892f-05829277bd74" = false
