[canonical-tests]

# square of sum 1
# this test may not be in the suite but has not been intentionally rejected
# "e46c542b-31fc-4506-bcae-6b62b3268537" = false

# square of sum 5
# this test may not be in the suite but has not been intentionally rejected
# "9b3f96cb-638d-41ee-99b7-b4f9c0622948" = false

# square of sum 100
# this test may not be in the suite but has not been intentionally rejected
# "54ba043f-3c35-4d43-86ff-3a41625d5e86" = false

# sum of squares 1
# this test may not be in the suite but has not been intentionally rejected
# "01d84507-b03e-4238-9395-dd61d03074b5" = false

# sum of squares 5
# this test may not be in the suite but has not been intentionally rejected
# "c93900cd-8cc2-4ca4-917b-dd3027023499" = false

# sum of squares 100
# this test may not be in the suite but has not been intentionally rejected
# "94807386-73e4-4d9e-8dec-69eb135b19e4" = false

# difference of squares 1
# this test may not be in the suite but has not been intentionally rejected
# "44f72ae6-31a7-437f-858d-2c0837adabb6" = false

# difference of squares 5
# this test may not be in the suite but has not been intentionally rejected
# "005cb2bf-a0c8-46f3-ae25-924029f8b00b" = false

# difference of squares 100
# this test may not be in the suite but has not been intentionally rejected
# "b1bf19de-9a16-41c0-a62b-1f02ecc0b036" = false
