[canonical-tests]

# word beginning with a
# this test may not be in the suite but has not been intentionally rejected
# "11567f84-e8c6-4918-aedb-435f0b73db57" = false

# word beginning with e
# this test may not be in the suite but has not been intentionally rejected
# "f623f581-bc59-4f45-9032-90c3ca9d2d90" = false

# word beginning with i
# this test may not be in the suite but has not been intentionally rejected
# "7dcb08b3-23a6-4e8a-b9aa-d4e859450d58" = false

# word beginning with o
# this test may not be in the suite but has not been intentionally rejected
# "0e5c3bff-266d-41c8-909f-364e4d16e09c" = false

# word beginning with u
# this test may not be in the suite but has not been intentionally rejected
# "614ba363-ca3c-4e96-ab09-c7320799723c" = false

# word beginning with a vowel and followed by a qu
# this test may not be in the suite but has not been intentionally rejected
# "bf2538c6-69eb-4fa7-a494-5a3fec911326" = false

# word beginning with p
# this test may not be in the suite but has not been intentionally rejected
# "e5be8a01-2d8a-45eb-abb4-3fcc9582a303" = false

# word beginning with k
# this test may not be in the suite but has not been intentionally rejected
# "d36d1e13-a7ed-464d-a282-8820cb2261ce" = false

# word beginning with x
# this test may not be in the suite but has not been intentionally rejected
# "d838b56f-0a89-4c90-b326-f16ff4e1dddc" = false

# word beginning with q without a following u
# this test may not be in the suite but has not been intentionally rejected
# "bce94a7a-a94e-4e2b-80f4-b2bb02e40f71" = false

# word beginning with ch
# this test may not be in the suite but has not been intentionally rejected
# "c01e049a-e3e2-451c-bf8e-e2abb7e438b8" = false

# word beginning with qu
# this test may not be in the suite but has not been intentionally rejected
# "9ba1669e-c43f-4b93-837a-cfc731fd1425" = false

# word beginning with qu and a preceding consonant
# this test may not be in the suite but has not been intentionally rejected
# "92e82277-d5e4-43d7-8dd3-3a3b316c41f7" = false

# word beginning with th
# this test may not be in the suite but has not been intentionally rejected
# "79ae4248-3499-4d5b-af46-5cb05fa073ac" = false

# word beginning with thr
# this test may not be in the suite but has not been intentionally rejected
# "e0b3ae65-f508-4de3-8999-19c2f8e243e1" = false

# word beginning with sch
# this test may not be in the suite but has not been intentionally rejected
# "20bc19f9-5a35-4341-9d69-1627d6ee6b43" = false

# word beginning with yt
# this test may not be in the suite but has not been intentionally rejected
# "54b796cb-613d-4509-8c82-8fbf8fc0af9e" = false

# word beginning with xr
# this test may not be in the suite but has not been intentionally rejected
# "8c37c5e1-872e-4630-ba6e-d20a959b67f6" = false

# y is treated like a consonant at the beginning of a word
# this test may not be in the suite but has not been intentionally rejected
# "a4a36d33-96f3-422c-a233-d4021460ff00" = false

# y is treated like a vowel at the end of a consonant cluster
# this test may not be in the suite but has not been intentionally rejected
# "adc90017-1a12-4100-b595-e346105042c7" = false

# y as second letter in two letter word
# this test may not be in the suite but has not been intentionally rejected
# "29b4ca3d-efe5-4a95-9a54-8467f2e5e59a" = false

# a whole phrase
# this test may not be in the suite but has not been intentionally rejected
# "44616581-5ce3-4a81-82d0-40c7ab13d2cf" = false
