version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  # Enable updates to the dependencies of our Dockerfile
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
