# Example markdownlint YAML configuration with all properties set to their default value

# Default state for all rules
default: false

# Path to configuration file to extend
extends: null

# MD001/heading-increment/header-increment - Heading levels should only increment by one level at a time
MD001: true
# MD002/first-heading-h1/first-header-h1 - First heading should be a top-level heading
MD002:
  # Heading level
  level: 1

# MD003/heading-style/header-style - Heading style
MD003:
  # Heading style
  style: "atx"

MD009: true
MD013: false
# MD014/commands-show-output - Dollar signs used before commands without showing output
MD014: false

