[canonical-tests]

# single digit strings can not be valid
"792a7082-feb7-48c7-b88b-bbfec160865e" = true

# a single zero is invalid
"698a7924-64d4-4d89-8daa-32e1aadc271e" = true

# a simple valid SIN that remains valid if reversed
"73c2f62b-9b10-4c9f-9a04-83cee7367965" = true

# a simple valid SIN that becomes invalid if reversed
"9369092e-b095-439f-948d-498bd076be11" = true

# a valid Canadian SIN
"8f9f2350-1faf-4008-ba84-85cbb93ffeca" = true

# invalid Canadian SIN
"1cdcf269-6560-44fc-91f6-5819a7548737" = true

# invalid credit card
"656c48c1-34e8-4e60-9a5a-aad8a367810a" = true

# invalid long number with an even remainder
"20e67fad-2121-43ed-99a8-14b5b856adb9" = true

# valid number with an even number of digits
"ad2a0c5f-84ed-4e5b-95da-6011d6f4f0aa" = true

# valid number with an odd number of spaces
"ef081c06-a41f-4761-8492-385e13c8202d" = true

# valid strings with a non-digit added at the end become invalid
"bef66f64-6100-4cbb-8f94-4c9713c5e5b2" = true

# valid strings with punctuation included become invalid
"2177e225-9ce7-40f6-b55d-fa420e62938e" = true

# valid strings with symbols included become invalid
"ebf04f27-9698-45e1-9afe-7e0851d0fe8d" = true

# single zero with space is invalid
"08195c5e-ce7f-422c-a5eb-3e45fece68ba" = true

# more than a single zero is valid
"12e63a3c-f866-4a79-8c14-b359fc386091" = true

# input digit 9 is correctly converted to output digit 9
"ab56fa80-5de8-4735-8a4a-14dae588663e" = true

# using ascii value for non-doubled non-digit isn't allowed
"39a06a5a-5bad-4e0f-b215-b042d46209b1" = true

# using ascii value for doubled non-digit isn't allowed
"f94cf191-a62f-4868-bc72-7253114aa157" = true
