[canonical-tests]

# count one word
# this test may not be in the suite but has not been intentionally rejected
# "61559d5f-2cad-48fb-af53-d3973a9ee9ef" = false

# count one of each word
# this test may not be in the suite but has not been intentionally rejected
# "5abd53a3-1aed-43a4-a15a-29f88c09cbbd" = false

# multiple occurrences of a word
# this test may not be in the suite but has not been intentionally rejected
# "2a3091e5-952e-4099-9fac-8f85d9655c0e" = false

# handles cramped lists
# this test may not be in the suite but has not been intentionally rejected
# "e81877ae-d4da-4af4-931c-d923cd621ca6" = false

# handles expanded lists
# this test may not be in the suite but has not been intentionally rejected
# "7349f682-9707-47c0-a9af-be56e1e7ff30" = false

# ignore punctuation
# this test may not be in the suite but has not been intentionally rejected
# "a514a0f2-8589-4279-8892-887f76a14c82" = false

# include numbers
# this test may not be in the suite but has not been intentionally rejected
# "d2e5cee6-d2ec-497b-bdc9-3ebe092ce55e" = false

# normalize case
# this test may not be in the suite but has not been intentionally rejected
# "dac6bc6a-21ae-4954-945d-d7f716392dbf" = false

# with apostrophes
"4185a902-bdb0-4074-864c-f416e42a0f19" = true

# with quotations
"be72af2b-8afe-4337-b151-b297202e4a7b" = true

# substrings from the beginning
# this test may not be in the suite but has not been intentionally rejected
# "8d6815fe-8a51-4a65-96f9-2fb3f6dc6ed6" = false

# multiple spaces not detected as a word
"c5f4ef26-f3f7-4725-b314-855c04fb4c13" = true

# alternating word separators not detected as a word
# this test may not be in the suite but has not been intentionally rejected
# "50176e8a-fe8e-4f4c-b6b6-aa9cf8f20360" = false
