[canonical-tests]

# no multiples within limit
"54aaab5a-ce86-4edc-8b40-d3ab2400a279" = true

# one factor has multiples within limit
"361e4e50-c89b-4f60-95ef-5bc5c595490a" = true

# more than one multiple within limit
"e644e070-040e-4ae0-9910-93c69fc3f7ce" = true

# more than one factor with multiples within limit
"607d6eb9-535c-41ce-91b5-3a61da3fa57f" = true

# each multiple is only counted once
"f47e8209-c0c5-4786-b07b-dc273bf86b9b" = true

# a much larger limit
"28c4b267-c980-4054-93e9-07723db615ac" = true

# three factors
"09c4494d-ff2d-4e0f-8421-f5532821ee12" = true

# factors not relatively prime
"2d0d5faa-f177-4ad6-bde9-ebb865083751" = true

# some pairs of factors relatively prime and some not
"ece8f2e8-96aa-4166-bbb7-6ce71261e354" = true

# one factor is a multiple of another
"624fdade-6ffb-400e-8472-456a38c171c0" = true

# much larger factors
"949ee7eb-db51-479c-b5cb-4a22b40ac057" = true

# all numbers are multiples of 1
"41093673-acbd-482c-ab80-d00a0cbedecd" = true

# no factors means an empty sum
"1730453b-baaa-438e-a9c2-d754497b2a76" = true

# the only multiple of 0 is 0
"214a01e9-f4bf-45bb-80f1-1dce9fbb0310" = true

# the factor 0 does not affect the sum of multiples of other factors
"c423ae21-a0cb-4ec7-aeb1-32971af5b510" = true

# solutions using include-exclude must extend to cardinality greater than 3
"17053ba9-112f-4ac0-aadb-0519dd836342" = true
