[canonical-tests]

# Empty RNA sequence
# this test may not be in the suite but has not been intentionally rejected
# "b4631f82-c98c-4a2f-90b3-c5c2b6c6f661" = false

# RNA complement of cytosine is guanine
# this test may not be in the suite but has not been intentionally rejected
# "a9558a3c-318c-4240-9256-5d5ed47005a6" = false

# RNA complement of guanine is cytosine
# this test may not be in the suite but has not been intentionally rejected
# "6eedbb5c-12cb-4c8b-9f51-f8320b4dc2e7" = false

# RNA complement of thymine is adenine
# this test may not be in the suite but has not been intentionally rejected
# "870bd3ec-8487-471d-8d9a-a25046488d3e" = false

# RNA complement of adenine is uracil
# this test may not be in the suite but has not been intentionally rejected
# "aade8964-02e1-4073-872f-42d3ffd74c5f" = false

# RNA complement
# this test may not be in the suite but has not been intentionally rejected
# "79ed2757-f018-4f47-a1d7-34a559392dbf" = false
