[canonical-tests]

# queen with a valid position
# this test may not be in the suite but has not been intentionally rejected
# "3ac4f735-d36c-44c4-a3e2-316f79704203" = false

# queen must have positive row
# this test may not be in the suite but has not been intentionally rejected
# "4e812d5d-b974-4e38-9a6b-8e0492bfa7be" = false

# queen must have row on board
# this test may not be in the suite but has not been intentionally rejected
# "f07b7536-b66b-4f08-beb9-4d70d891d5c8" = false

# queen must have positive column
# this test may not be in the suite but has not been intentionally rejected
# "15a10794-36d9-4907-ae6b-e5a0d4c54ebe" = false

# queen must have column on board
# this test may not be in the suite but has not been intentionally rejected
# "6907762d-0e8a-4c38-87fb-12f2f65f0ce4" = false

# can not attack
# this test may not be in the suite but has not been intentionally rejected
# "33ae4113-d237-42ee-bac1-e1e699c0c007" = false

# can attack on same row
# this test may not be in the suite but has not been intentionally rejected
# "eaa65540-ea7c-4152-8c21-003c7a68c914" = false

# can attack on same column
# this test may not be in the suite but has not been intentionally rejected
# "bae6f609-2c0e-4154-af71-af82b7c31cea" = false

# can attack on first diagonal
# this test may not be in the suite but has not been intentionally rejected
# "0e1b4139-b90d-4562-bd58-dfa04f1746c7" = false

# can attack on second diagonal
# this test may not be in the suite but has not been intentionally rejected
# "ff9b7ed4-e4b6-401b-8d16-bc894d6d3dcd" = false

# can attack on third diagonal
# this test may not be in the suite but has not been intentionally rejected
# "0a71e605-6e28-4cc2-aa47-d20a2e71037a" = false

# can attack on fourth diagonal
# this test may not be in the suite but has not been intentionally rejected
# "0790b588-ae73-4f1f-a968-dd0b34f45f86" = false
