{% import "macros.rs" as macros -%}

//! Tests for {{ exercise }}
//!
//! Generated by [utility][utility] using [canonical data][canonical_data]
//!
//! [utility]: https://github.com/exercism/rust/tree/main/util/exercise
//! [canonical_data]: https://raw.githubusercontent.com/exercism/problem-specifications/main/exercises/{{ exercise }}/canonical-data.json

{% for comment in comments -%}
/// {{ comment }}
{% endfor %}

{% if use_maplit -%}
use maplit::hashmap;
{% endif %}

{% for property in properties | sort -%}
{% include "property_fn.rs" %}
{% endfor -%}

{# Don't ignore the first case. -#}
{% set first_test_case = true -%}

{% for item in cases -%}
    {# Check if we're dealing with a group of cases. #}
    {% if item.cases -%}
        /// {{ item.description }}
        {% if item.optional -%}
        /// {{ item.optional }}
        {% endif -%}

        {% if item.comments -%}
            {% for comment in item.comments -%}
            /// {{ comment }}
            {% endfor -%}
        {% endif -%}

        {% for case in item.cases -%}
            {{ macros::gen_test_fn(case=case, first_test_case=first_test_case) }}
            {% set_global first_test_case = false -%}
        {% endfor -%}

    {# Or just a single one. #}
    {% else -%}
        {{ macros::gen_test_fn(case=item, first_test_case=first_test_case) }}
        {% set_global first_test_case = false -%}
    {% endif -%}
{% endfor -%}
