[canonical-tests]

# Chromatic scale with sharps
# this test may not be in the suite but has not been intentionally rejected
# "10ea7b14-8a49-40be-ac55-7c62b55f9b47" = false

# Chromatic scale with flats
# this test may not be in the suite but has not been intentionally rejected
# "af8381de-9a72-4efd-823a-48374dbfe76f" = false

# Simple major scale
# this test may not be in the suite but has not been intentionally rejected
# "6f5b1410-1dd7-4c6c-b410-6b7e986f6f1e" = false

# Major scale with sharps
# this test may not be in the suite but has not been intentionally rejected
# "13a92f89-a83e-40b5-b9d4-01136931ba02" = false

# Major scale with flats
# this test may not be in the suite but has not been intentionally rejected
# "aa3320f6-a761-49a1-bcf6-978e0c81080a" = false

# Minor scale with sharps
# this test may not be in the suite but has not been intentionally rejected
# "63daeb2f-c3f9-4c45-92be-5bf97f61ff94" = false

# Minor scale with flats
# this test may not be in the suite but has not been intentionally rejected
# "616594d0-9c48-4301-949e-af1d4fad16fd" = false

# Dorian mode
# this test may not be in the suite but has not been intentionally rejected
# "390bd12c-5ac7-4ec7-bdde-4e58d5c78b0a" = false

# Mixolydian mode
# this test may not be in the suite but has not been intentionally rejected
# "846d0862-0f3e-4f3b-8a2d-9cc74f017848" = false

# Lydian mode
# this test may not be in the suite but has not been intentionally rejected
# "7d49a8bb-b5f7-46ad-a207-83bd5032291a" = false

# Phrygian mode
# this test may not be in the suite but has not been intentionally rejected
# "a4e4dac5-1891-4160-a19f-bb06d653d4d0" = false

# Locrian mode
# this test may not be in the suite but has not been intentionally rejected
# "ef3650af-90f8-4ad9-9ef6-fdbeae07dcaa" = false

# Harmonic minor
# this test may not be in the suite but has not been intentionally rejected
# "70517400-12b7-4530-b861-fa940ae69ee8" = false

# Octatonic
"37114c0b-c54d-45da-9f4b-3848201470b0" = true

# Hexatonic
"496466e7-aa45-4bbd-a64d-f41030feed9c" = true

# Pentatonic
"bee5d9ec-e226-47b6-b62b-847a9241f3cc" = true

# Enigmatic
"dbee06a6-7535-4ab7-98e8-d8a36c8402d1" = true
