[canonical-tests]

# empty strand
# this test may not be in the suite but has not been intentionally rejected
# "3e5c30a8-87e2-4845-a815-a49671ade970" = false

# can count one nucleotide in single-character input
# this test may not be in the suite but has not been intentionally rejected
# "a0ea42a6-06d9-4ac6-828c-7ccaccf98fec" = false

# strand with repeated nucleotide
# this test may not be in the suite but has not been intentionally rejected
# "eca0d565-ed8c-43e7-9033-6cefbf5115b5" = false

# strand with multiple nucleotides
# this test may not be in the suite but has not been intentionally rejected
# "40a45eac-c83f-4740-901a-20b22d15a39f" = false

# strand with invalid nucleotides
# this test may not be in the suite but has not been intentionally rejected
# "b4c47851-ee9e-4b0a-be70-a86e343bd851" = false
