[canonical-tests]

# empty lists
# this test may not be in the suite but has not been intentionally rejected
# "97319c93-ebc5-47ab-a022-02a1980e1d29" = false

# empty list within non empty list
# this test may not be in the suite but has not been intentionally rejected
# "de27dbd4-df52-46fe-a336-30be58457382" = false

# non empty list contains empty list
# this test may not be in the suite but has not been intentionally rejected
# "5487cfd1-bc7d-429f-ac6f-1177b857d4fb" = false

# list equals itself
# this test may not be in the suite but has not been intentionally rejected
# "1f390b47-f6b2-4a93-bc23-858ba5dda9a6" = false

# different lists
# this test may not be in the suite but has not been intentionally rejected
# "7ed2bfb2-922b-4363-ae75-f3a05e8274f5" = false

# false start
# this test may not be in the suite but has not been intentionally rejected
# "3b8a2568-6144-4f06-b0a1-9d266b365341" = false

# consecutive
# this test may not be in the suite but has not been intentionally rejected
# "dc39ed58-6311-4814-be30-05a64bc8d9b1" = false

# sublist at start
# this test may not be in the suite but has not been intentionally rejected
# "d1270dab-a1ce-41aa-b29d-b3257241ac26" = false

# sublist in middle
"81f3d3f7-4f25-4ada-bcdc-897c403de1b6" = true

# sublist at end
"43bcae1e-a9cf-470e-923e-0946e04d8fdd" = true

# at start of superlist
# this test may not be in the suite but has not been intentionally rejected
# "76cf99ed-0ff0-4b00-94af-4dfb43fe5caa" = false

# in middle of superlist
# this test may not be in the suite but has not been intentionally rejected
# "b83989ec-8bdf-4655-95aa-9f38f3e357fd" = false

# at end of superlist
# this test may not be in the suite but has not been intentionally rejected
# "26f9f7c3-6cf6-4610-984a-662f71f8689b" = false

# first list missing element from second list
# this test may not be in the suite but has not been intentionally rejected
# "0a6db763-3588-416a-8f47-76b1cedde31e" = false

# second list missing element from first list
# this test may not be in the suite but has not been intentionally rejected
# "83ffe6d8-a445-4a3c-8795-1e51a95e65c3" = false

# order matters to a list
# this test may not be in the suite but has not been intentionally rejected
# "0d7ee7c1-0347-45c8-9ef5-b88db152b30b" = false

# same digits but different numbers
# this test may not be in the suite but has not been intentionally rejected
# "5f47ce86-944e-40f9-9f31-6368aad70aa6" = false
