[canonical-tests]

# not allergic to anything
# this test may not be in the suite but has not been intentionally rejected
# "17fc7296-2440-4ac4-ad7b-d07c321bc5a0" = false

# allergic only to eggs
# this test may not be in the suite but has not been intentionally rejected
# "07ced27b-1da5-4c2e-8ae2-cb2791437546" = false

# allergic to eggs and something else
# this test may not be in the suite but has not been intentionally rejected
# "5035b954-b6fa-4b9b-a487-dae69d8c5f96" = false

# allergic to something, but not eggs
# this test may not be in the suite but has not been intentionally rejected
# "64a6a83a-5723-4b5b-a896-663307403310" = false

# allergic to everything
"90c8f484-456b-41c4-82ba-2d08d93231c6" = true

# not allergic to anything
# this test may not be in the suite but has not been intentionally rejected
# "d266a59a-fccc-413b-ac53-d57cb1f0db9d" = false

# allergic only to peanuts
# this test may not be in the suite but has not been intentionally rejected
# "ea210a98-860d-46b2-a5bf-50d8995b3f2a" = false

# allergic to peanuts and something else
# this test may not be in the suite but has not been intentionally rejected
# "eac69ae9-8d14-4291-ac4b-7fd2c73d3a5b" = false

# allergic to something, but not peanuts
# this test may not be in the suite but has not been intentionally rejected
# "9152058c-ce39-4b16-9b1d-283ec6d25085" = false

# allergic to everything
"d2d71fd8-63d5-40f9-a627-fbdaf88caeab" = true

# not allergic to anything
# this test may not be in the suite but has not been intentionally rejected
# "b948b0a1-cbf7-4b28-a244-73ff56687c80" = false

# allergic only to shellfish
# this test may not be in the suite but has not been intentionally rejected
# "9ce9a6f3-53e9-4923-85e0-73019047c567" = false

# allergic to shellfish and something else
# this test may not be in the suite but has not been intentionally rejected
# "b272fca5-57ba-4b00-bd0c-43a737ab2131" = false

# allergic to something, but not shellfish
# this test may not be in the suite but has not been intentionally rejected
# "21ef8e17-c227-494e-8e78-470a1c59c3d8" = false

# allergic to everything
"cc789c19-2b5e-4c67-b146-625dc8cfa34e" = true

# not allergic to anything
# this test may not be in the suite but has not been intentionally rejected
# "651bde0a-2a74-46c4-ab55-02a0906ca2f5" = false

# allergic only to strawberries
# this test may not be in the suite but has not been intentionally rejected
# "b649a750-9703-4f5f-b7f7-91da2c160ece" = false

# allergic to strawberries and something else
# this test may not be in the suite but has not been intentionally rejected
# "50f5f8f3-3bac-47e6-8dba-2d94470a4bc6" = false

# allergic to something, but not strawberries
# this test may not be in the suite but has not been intentionally rejected
# "23dd6952-88c9-48d7-a7d5-5d0343deb18d" = false

# allergic to everything
"74afaae2-13b6-43a2-837a-286cd42e7d7e" = true

# not allergic to anything
# this test may not be in the suite but has not been intentionally rejected
# "c49a91ef-6252-415e-907e-a9d26ef61723" = false

# allergic only to tomatoes
# this test may not be in the suite but has not been intentionally rejected
# "b69c5131-b7d0-41ad-a32c-e1b2cc632df8" = false

# allergic to tomatoes and something else
# this test may not be in the suite but has not been intentionally rejected
# "1ca50eb1-f042-4ccf-9050-341521b929ec" = false

# allergic to something, but not tomatoes
# this test may not be in the suite but has not been intentionally rejected
# "e9846baa-456b-4eff-8025-034b9f77bd8e" = false

# allergic to everything
"b2414f01-f3ad-4965-8391-e65f54dad35f" = true

# not allergic to anything
# this test may not be in the suite but has not been intentionally rejected
# "978467ab-bda4-49f7-b004-1d011ead947c" = false

# allergic only to chocolate
# this test may not be in the suite but has not been intentionally rejected
# "59cf4e49-06ea-4139-a2c1-d7aad28f8cbc" = false

# allergic to chocolate and something else
# this test may not be in the suite but has not been intentionally rejected
# "b0a7c07b-2db7-4f73-a180-565e07040ef1" = false

# allergic to something, but not chocolate
# this test may not be in the suite but has not been intentionally rejected
# "f5506893-f1ae-482a-b516-7532ba5ca9d2" = false

# allergic to everything
"02debb3d-d7e2-4376-a26b-3c974b6595c6" = true

# not allergic to anything
# this test may not be in the suite but has not been intentionally rejected
# "17f4a42b-c91e-41b8-8a76-4797886c2d96" = false

# allergic only to pollen
# this test may not be in the suite but has not been intentionally rejected
# "7696eba7-1837-4488-882a-14b7b4e3e399" = false

# allergic to pollen and something else
# this test may not be in the suite but has not been intentionally rejected
# "9a49aec5-fa1f-405d-889e-4dfc420db2b6" = false

# allergic to something, but not pollen
# this test may not be in the suite but has not been intentionally rejected
# "3cb8e79f-d108-4712-b620-aa146b1954a9" = false

# allergic to everything
"1dc3fe57-7c68-4043-9d51-5457128744b2" = true

# not allergic to anything
# this test may not be in the suite but has not been intentionally rejected
# "d3f523d6-3d50-419b-a222-d4dfd62ce314" = false

# allergic only to cats
# this test may not be in the suite but has not been intentionally rejected
# "eba541c3-c886-42d3-baef-c048cb7fcd8f" = false

# allergic to cats and something else
# this test may not be in the suite but has not been intentionally rejected
# "ba718376-26e0-40b7-bbbe-060287637ea5" = false

# allergic to something, but not cats
# this test may not be in the suite but has not been intentionally rejected
# "3c6dbf4a-5277-436f-8b88-15a206f2d6c4" = false

# allergic to everything
"1faabb05-2b98-4995-9046-d83e4a48a7c1" = true

# no allergies
# this test may not be in the suite but has not been intentionally rejected
# "f9c1b8e7-7dc5-4887-aa93-cebdcc29dd8f" = false

# just eggs
# this test may not be in the suite but has not been intentionally rejected
# "9e1a4364-09a6-4d94-990f-541a94a4c1e8" = false

# just peanuts
# this test may not be in the suite but has not been intentionally rejected
# "8851c973-805e-4283-9e01-d0c0da0e4695" = false

# just strawberries
# this test may not be in the suite but has not been intentionally rejected
# "2c8943cb-005e-435f-ae11-3e8fb558ea98" = false

# eggs and peanuts
# this test may not be in the suite but has not been intentionally rejected
# "6fa95d26-044c-48a9-8a7b-9ee46ec32c5c" = false

# more than eggs but not peanuts
# this test may not be in the suite but has not been intentionally rejected
# "19890e22-f63f-4c5c-a9fb-fb6eacddfe8e" = false

# lots of stuff
# this test may not be in the suite but has not been intentionally rejected
# "4b68f470-067c-44e4-889f-c9fe28917d2f" = false

# everything
# this test may not be in the suite but has not been intentionally rejected
# "0881b7c5-9efa-4530-91bd-68370d054bc7" = false

# no allergen score parts
# this test may not be in the suite but has not been intentionally rejected
# "12ce86de-b347-42a0-ab7c-2e0570f0c65b" = false
