[canonical-tests]

# Can encode
# this test may not be in the suite but has not been intentionally rejected
# "b8bdfbe1-bea3-41bb-a999-b41403f2b15d" = false

# Can decode
# this test may not be in the suite but has not been intentionally rejected
# "3dff7f36-75db-46b4-ab70-644b3f38b81c" = false

# Is reversible. I.e., if you apply decode in a encoded result, you must see the same plaintext encode parameter as a result of the decode method
# this test may not be in the suite but has not been intentionally rejected
# "8143c684-6df6-46ba-bd1f-dea8fcb5d265" = false

# Key is made only of lowercase letters
# this test may not be in the suite but has not been intentionally rejected
# "defc0050-e87d-4840-85e4-51a1ab9dd6aa" = false

# Can encode
# this test may not be in the suite but has not been intentionally rejected
# "565e5158-5b3b-41dd-b99d-33b9f413c39f" = false

# Can decode
# this test may not be in the suite but has not been intentionally rejected
# "d44e4f6a-b8af-4e90-9d08-fd407e31e67b" = false

# Is reversible. I.e., if you apply decode in a encoded result, you must see the same plaintext encode parameter as a result of the decode method
# this test may not be in the suite but has not been intentionally rejected
# "70a16473-7339-43df-902d-93408c69e9d1" = false

# Can double shift encode
# this test may not be in the suite but has not been intentionally rejected
# "69a1458b-92a6-433a-a02d-7beac3ea91f9" = false

# Can wrap on encode
# this test may not be in the suite but has not been intentionally rejected
# "21d207c1-98de-40aa-994f-86197ae230fb" = false

# Can wrap on decode
# this test may not be in the suite but has not been intentionally rejected
# "a3d7a4d7-24a9-4de6-bdc4-a6614ced0cb3" = false

# Can encode messages longer than the key
# this test may not be in the suite but has not been intentionally rejected
# "e31c9b8c-8eb6-45c9-a4b5-8344a36b9641" = false

# Can decode messages longer than the key
# this test may not be in the suite but has not been intentionally rejected
# "93cfaae0-17da-4627-9a04-d6d1e1be52e3" = false
