[canonical-tests]

# empty strands
# this test may not be in the suite but has not been intentionally rejected
# "f6dcb64f-03b0-4b60-81b1-3c9dbf47e887" = false

# single letter identical strands
# this test may not be in the suite but has not been intentionally rejected
# "54681314-eee2-439a-9db0-b0636c656156" = false

# single letter different strands
# this test may not be in the suite but has not been intentionally rejected
# "294479a3-a4c8-478f-8d63-6209815a827b" = false

# long identical strands
# this test may not be in the suite but has not been intentionally rejected
# "9aed5f34-5693-4344-9b31-40c692fb5592" = false

# long different strands
# this test may not be in the suite but has not been intentionally rejected
# "cd2273a5-c576-46c8-a52b-dee251c3e6e5" = false

# disallow first strand longer
# this test may not be in the suite but has not been intentionally rejected
# "919f8ef0-b767-4d1b-8516-6379d07fcb28" = false

# disallow second strand longer
# this test may not be in the suite but has not been intentionally rejected
# "8a2d4ed0-ead5-4fdd-924d-27c4cf56e60e" = false

# disallow left empty strand
# this test may not be in the suite but has not been intentionally rejected
# "5dce058b-28d4-4ca7-aa64-adfe4e17784c" = false

# disallow right empty strand
# this test may not be in the suite but has not been intentionally rejected
# "38826d4b-16fb-4639-ac3e-ba027dec8b5f" = false
