[package]
name = "xtodo"
version = "0.1.0"
description = "An utility to track outdated or unimplemented exercises on the Rust track"

[dependencies]
clap = "2.32.0"
reqwest = "0.9.4"
serde_json = "1.0"
