[canonical-tests]

# no matches
# this test may not be in the suite but has not been intentionally rejected
# "dd40c4d2-3c8b-44e5-992a-f42b393ec373" = false

# detects two anagrams
# this test may not be in the suite but has not been intentionally rejected
# "b3cca662-f50a-489e-ae10-ab8290a09bdc" = false

# does not detect anagram subsets
# this test may not be in the suite but has not been intentionally rejected
# "a27558ee-9ba0-4552-96b1-ecf665b06556" = false

# detects anagram
# this test may not be in the suite but has not been intentionally rejected
# "64cd4584-fc15-4781-b633-3d814c4941a4" = false

# detects three anagrams
# this test may not be in the suite but has not been intentionally rejected
# "99c91beb-838f-4ccd-b123-935139917283" = false

# detects multiple anagrams with different case
# this test may not be in the suite but has not been intentionally rejected
# "78487770-e258-4e1f-a646-8ece10950d90" = false

# does not detect non-anagrams with identical checksum
# this test may not be in the suite but has not been intentionally rejected
# "1d0ab8aa-362f-49b7-9902-3d0c668d557b" = false

# detects anagrams case-insensitively
# this test may not be in the suite but has not been intentionally rejected
# "9e632c0b-c0b1-4804-8cc1-e295dea6d8a8" = false

# detects anagrams using case-insensitive subject
# this test may not be in the suite but has not been intentionally rejected
# "b248e49f-0905-48d2-9c8d-bd02d8c3e392" = false

# detects anagrams using case-insensitive possible matches
# this test may not be in the suite but has not been intentionally rejected
# "f367325c-78ec-411c-be76-e79047f4bd54" = false

# does not detect an anagram if the original word is repeated
# this test may not be in the suite but has not been intentionally rejected
# "7cc195ad-e3c7-44ee-9fd2-d3c344806a2c" = false

# anagrams must use all letters exactly once
# this test may not be in the suite but has not been intentionally rejected
# "9878a1c9-d6ea-4235-ae51-3ea2befd6842" = false

# words are not anagrams of themselves (case-insensitive)
# this test may not be in the suite but has not been intentionally rejected
# "85757361-4535-45fd-ac0e-3810d40debc1" = false

# words other than themselves can be anagrams
# this test may not be in the suite but has not been intentionally rejected
# "a0705568-628c-4b55-9798-82e4acde51ca" = false
