[canonical-tests]

# stating something
# this test may not be in the suite but has not been intentionally rejected
# "e162fead-606f-437a-a166-d051915cea8e" = false

# shouting
"73a966dc-8017-47d6-bb32-cf07d1a5fcd9" = true

# shouting gibberish
# this test may not be in the suite but has not been intentionally rejected
# "d6c98afd-df35-4806-b55e-2c457c3ab748" = false

# asking a question
# this test may not be in the suite but has not been intentionally rejected
# "8a2e771d-d6f1-4e3f-b6c6-b41495556e37" = false

# asking a numeric question
# this test may not be in the suite but has not been intentionally rejected
# "81080c62-4e4d-4066-b30a-48d8d76920d9" = false

# asking gibberish
# this test may not be in the suite but has not been intentionally rejected
# "2a02716d-685b-4e2e-a804-2adaf281c01e" = false

# talking forcefully
# this test may not be in the suite but has not been intentionally rejected
# "c02f9179-ab16-4aa7-a8dc-940145c385f7" = false

# using acronyms in regular speech
# this test may not be in the suite but has not been intentionally rejected
# "153c0e25-9bb5-4ec5-966e-598463658bcd" = false

# forceful question
# this test may not be in the suite but has not been intentionally rejected
# "a5193c61-4a92-4f68-93e2-f554eb385ec6" = false

# shouting numbers
# this test may not be in the suite but has not been intentionally rejected
# "a20e0c54-2224-4dde-8b10-bd2cdd4f61bc" = false

# no letters
# this test may not be in the suite but has not been intentionally rejected
# "f7bc4b92-bdff-421e-a238-ae97f230ccac" = false

# question with no letters
# this test may not be in the suite but has not been intentionally rejected
# "bb0011c5-cd52-4a5b-8bfb-a87b6283b0e2" = false

# shouting with special characters
# this test may not be in the suite but has not been intentionally rejected
# "496143c8-1c31-4c01-8a08-88427af85c66" = false

# shouting with no exclamation mark
# this test may not be in the suite but has not been intentionally rejected
# "e6793c1c-43bd-4b8d-bc11-499aea73925f" = false

# statement containing question mark
# this test may not be in the suite but has not been intentionally rejected
# "aa8097cc-c548-4951-8856-14a404dd236a" = false

# non-letters with question
# this test may not be in the suite but has not been intentionally rejected
# "9bfc677d-ea3a-45f2-be44-35bc8fa3753e" = false

# prattling on
# this test may not be in the suite but has not been intentionally rejected
# "8608c508-f7de-4b17-985b-811878b3cf45" = false

# silence
"bc39f7c6-f543-41be-9a43-fd1c2f753fc0" = true

# prolonged silence
# this test may not be in the suite but has not been intentionally rejected
# "d6c47565-372b-4b09-b1dd-c40552b8378b" = false

# alternate silence
# this test may not be in the suite but has not been intentionally rejected
# "4428f28d-4100-4d85-a902-e5a78cb0ecd3" = false

# multiple line question
# this test may not be in the suite but has not been intentionally rejected
# "66953780-165b-4e7e-8ce3-4bcb80b6385a" = false

# starting with whitespace
# this test may not be in the suite but has not been intentionally rejected
# "5371ef75-d9ea-4103-bcfa-2da973ddec1b" = false

# ending with whitespace
# this test may not be in the suite but has not been intentionally rejected
# "05b304d6-f83b-46e7-81e0-4cd3ca647900" = false

# other whitespace
# this test may not be in the suite but has not been intentionally rejected
# "72bd5ad3-9b2f-4931-a988-dce1f5771de2" = false

# non-question ending with whitespace
# this test may not be in the suite but has not been intentionally rejected
# "12983553-8601-46a8-92fa-fcaa3bc4a2a0" = false
