[canonical-tests]

# date only specification of time
# this test may not be in the suite but has not been intentionally rejected
# "92fbe71c-ea52-4fac-bd77-be38023cacf7" = false

# second test for date only specification of time
# this test may not be in the suite but has not been intentionally rejected
# "6d86dd16-6f7a-47be-9e58-bb9fb2ae1433" = false

# third test for date only specification of time
# this test may not be in the suite but has not been intentionally rejected
# "77eb8502-2bca-4d92-89d9-7b39ace28dd5" = false

# full time specified
# this test may not be in the suite but has not been intentionally rejected
# "c9d89a7d-06f8-4e28-a305-64f1b2abc693" = false

# full time with day roll-over
# this test may not be in the suite but has not been intentionally rejected
# "09d4e30e-728a-4b52-9005-be44a58d9eba" = false
