[canonical-tests]

# Degenerate case with a single 'A' row
"202fb4cc-6a38-4883-9193-a29d5cb92076" = true

# Degenerate case with no row containing 3 distinct groups of spaces
"bd6a6d78-9302-42e9-8f60-ac1461e9abae" = true

# Smallest non-degenerate case with odd diamond side length
"af8efb49-14ed-447f-8944-4cc59ce3fd76" = true

# Smallest non-degenerate case with even diamond side length
"e0c19a95-9888-4d05-86a0-fa81b9e70d1d" = true

# Largest possible diamond
"82ea9aa9-4c0e-442a-b07e-40204e925944" = true
