[canonical-tests]

# cleans the number
# this test may not be in the suite but has not been intentionally rejected
# "79666dce-e0f1-46de-95a1-563802913c35" = false

# cleans numbers with dots
# this test may not be in the suite but has not been intentionally rejected
# "c360451f-549f-43e4-8aba-fdf6cb0bf83f" = false

# cleans numbers with multiple spaces
# this test may not be in the suite but has not been intentionally rejected
# "08f94c34-9a37-46a2-a123-2a8e9727395d" = false

# invalid when 9 digits
# this test may not be in the suite but has not been intentionally rejected
# "598d8432-0659-4019-a78b-1c6a73691d21" = false

# invalid when 11 digits does not start with a 1
# this test may not be in the suite but has not been intentionally rejected
# "57061c72-07b5-431f-9766-d97da7c4399d" = false

# valid when 11 digits and starting with 1
# this test may not be in the suite but has not been intentionally rejected
# "9962cbf3-97bb-4118-ba9b-38ff49c64430" = false

# valid when 11 digits and starting with 1 even with punctuation
# this test may not be in the suite but has not been intentionally rejected
# "fa724fbf-054c-4d91-95da-f65ab5b6dbca" = false

# invalid when more than 11 digits
# this test may not be in the suite but has not been intentionally rejected
# "c6a5f007-895a-4fc5-90bc-a7e70f9b5cad" = false

# invalid with letters
# this test may not be in the suite but has not been intentionally rejected
# "63f38f37-53f6-4a5f-bd86-e9b404f10a60" = false

# invalid with punctuations
# this test may not be in the suite but has not been intentionally rejected
# "4bd97d90-52fd-45d3-b0db-06ab95b1244e" = false

# invalid if area code starts with 0
# this test may not be in the suite but has not been intentionally rejected
# "d77d07f8-873c-4b17-8978-5f66139bf7d7" = false

# invalid if area code starts with 1
# this test may not be in the suite but has not been intentionally rejected
# "c7485cfb-1e7b-4081-8e96-8cdb3b77f15e" = false

# invalid if exchange code starts with 0
# this test may not be in the suite but has not been intentionally rejected
# "4d622293-6976-413d-b8bf-dd8a94d4e2ac" = false

# invalid if exchange code starts with 1
# this test may not be in the suite but has not been intentionally rejected
# "4cef57b4-7d8e-43aa-8328-1e1b89001262" = false

# invalid if area code starts with 0 on valid 11-digit number
# this test may not be in the suite but has not been intentionally rejected
# "9925b09c-1a0d-4960-a197-5d163cbe308c" = false

# invalid if area code starts with 1 on valid 11-digit number
# this test may not be in the suite but has not been intentionally rejected
# "3f809d37-40f3-44b5-ad90-535838b1a816" = false

# invalid if exchange code starts with 0 on valid 11-digit number
# this test may not be in the suite but has not been intentionally rejected
# "e08e5532-d621-40d4-b0cc-96c159276b65" = false

# invalid if exchange code starts with 1 on valid 11-digit number
# this test may not be in the suite but has not been intentionally rejected
# "57b32f3d-696a-455c-8bf1-137b6d171cdf" = false
