[canonical-tests]

# lowercase letter
# this test may not be in the suite but has not been intentionally rejected
# "f46cda29-1ca5-4ef2-bd45-388a767e3db2" = false

# uppercase letter
# this test may not be in the suite but has not been intentionally rejected
# "f7794b49-f13e-45d1-a933-4e48459b2201" = false

# valuable letter
# this test may not be in the suite but has not been intentionally rejected
# "eaba9c76-f9fa-49c9-a1b0-d1ba3a5b31fa" = false

# short word
# this test may not be in the suite but has not been intentionally rejected
# "f3c8c94e-bb48-4da2-b09f-e832e103151e" = false

# short, valuable word
# this test may not be in the suite but has not been intentionally rejected
# "71e3d8fa-900d-4548-930e-68e7067c4615" = false

# medium word
"d3088ad9-570c-4b51-8764-c75d5a430e99" = true

# medium, valuable word
# this test may not be in the suite but has not been intentionally rejected
# "fa20c572-ad86-400a-8511-64512daac352" = false

# long, mixed-case word
# this test may not be in the suite but has not been intentionally rejected
# "9336f0ba-9c2b-4fa0-bd1c-2e2d328cf967" = false

# english-like word
# this test may not be in the suite but has not been intentionally rejected
# "1e34e2c3-e444-4ea7-b598-3c2b46fd2c10" = false

# empty input
# this test may not be in the suite but has not been intentionally rejected
# "4efe3169-b3b6-4334-8bae-ff4ef24a7e4f" = false

# entire alphabet available
# this test may not be in the suite but has not been intentionally rejected
# "3b305c1c-f260-4e15-a5b5-cb7d3ea7c3d7" = false
