[canonical-tests]

# zero steps for one
# this test may not be in the suite but has not been intentionally rejected
# "540a3d51-e7a6-47a5-92a3-4ad1838f0bfd" = false

# divide if even
# this test may not be in the suite but has not been intentionally rejected
# "3d76a0a6-ea84-444a-821a-f7857c2c1859" = false

# even and odd steps
# this test may not be in the suite but has not been intentionally rejected
# "754dea81-123c-429e-b8bc-db20b05a87b9" = false

# large number of even and odd steps
# this test may not be in the suite but has not been intentionally rejected
# "ecfd0210-6f85-44f6-8280-f65534892ff6" = false

# zero is an error
# this test may not be in the suite but has not been intentionally rejected
# "7d4750e6-def9-4b86-aec7-9f7eb44f95a3" = false

# negative value is an error
# this test may not be in the suite but has not been intentionally rejected
# "c6c795bf-a288-45e9-86a1-841359ad426d" = false
