[canonical-tests]

# single hand always wins
# this test may not be in the suite but has not been intentionally rejected
# "161f485e-39c2-4012-84cf-bec0c755b66c" = false

# highest card out of all hands wins
# this test may not be in the suite but has not been intentionally rejected
# "370ac23a-a00f-48a9-9965-6f3fb595cf45" = false

# a tie has multiple winners
# this test may not be in the suite but has not been intentionally rejected
# "d94ad5a7-17df-484b-9932-c64fc26cff52" = false

# multiple hands with the same high cards, tie compares next highest ranked, down to last card
# this test may not be in the suite but has not been intentionally rejected
# "61ed83a9-cfaa-40a5-942a-51f52f0a8725" = false

# one pair beats high card
# this test may not be in the suite but has not been intentionally rejected
# "f7175a89-34ff-44de-b3d7-f6fd97d1fca4" = false

# highest pair wins
# this test may not be in the suite but has not been intentionally rejected
# "e114fd41-a301-4111-a9e7-5a7f72a76561" = false

# two pairs beats one pair
# this test may not be in the suite but has not been intentionally rejected
# "935bb4dc-a622-4400-97fa-86e7d06b1f76" = false

# both hands have two pairs, highest ranked pair wins
# this test may not be in the suite but has not been intentionally rejected
# "c8aeafe1-6e3d-4711-a6de-5161deca91fd" = false

# both hands have two pairs, with the same highest ranked pair, tie goes to low pair
# this test may not be in the suite but has not been intentionally rejected
# "88abe1ba-7ad7-40f3-847e-0a26f8e46a60" = false

# both hands have two identically ranked pairs, tie goes to remaining card (kicker)
# this test may not be in the suite but has not been intentionally rejected
# "15a7a315-0577-47a3-9981-d6cf8e6f387b" = false

# three of a kind beats two pair
# this test may not be in the suite but has not been intentionally rejected
# "21e9f1e6-2d72-49a1-a930-228e5e0195dc" = false

# both hands have three of a kind, tie goes to highest ranked triplet
# this test may not be in the suite but has not been intentionally rejected
# "c2fffd1f-c287-480f-bf2d-9628e63bbcc3" = false

# with multiple decks, two players can have same three of a kind, ties go to highest remaining cards
# this test may not be in the suite but has not been intentionally rejected
# "eb856cc2-481c-4b0d-9835-4d75d07a5d9d" = false

# a straight beats three of a kind
# this test may not be in the suite but has not been intentionally rejected
# "a858c5d9-2f28-48e7-9980-b7fa04060a60" = false

# aces can end a straight (10 J Q K A)
# this test may not be in the suite but has not been intentionally rejected
# "73c9c756-e63e-4b01-a88d-0d4491a7a0e3" = false

# aces can start a straight (A 2 3 4 5)
# this test may not be in the suite but has not been intentionally rejected
# "76856b0d-35cd-49ce-a492-fe5db53abc02" = false

# both hands with a straight, tie goes to highest ranked card
# this test may not be in the suite but has not been intentionally rejected
# "6980c612-bbff-4914-b17a-b044e4e69ea1" = false

# even though an ace is usually high, a 5-high straight is the lowest-scoring straight
# this test may not be in the suite but has not been intentionally rejected
# "5135675c-c2fc-4e21-9ba3-af77a32e9ba4" = false

# flush beats a straight
# this test may not be in the suite but has not been intentionally rejected
# "c601b5e6-e1df-4ade-b444-b60ce13b2571" = false

# both hands have a flush, tie goes to high card, down to the last one if necessary
# this test may not be in the suite but has not been intentionally rejected
# "4d90261d-251c-49bd-a468-896bf10133de" = false

# full house beats a flush
# this test may not be in the suite but has not been intentionally rejected
# "3a19361d-8974-455c-82e5-f7152f5dba7c" = false

# both hands have a full house, tie goes to highest-ranked triplet
# this test may not be in the suite but has not been intentionally rejected
# "eb73d0e6-b66c-4f0f-b8ba-bf96bc0a67f0" = false

# with multiple decks, both hands have a full house with the same triplet, tie goes to the pair
# this test may not be in the suite but has not been intentionally rejected
# "34b51168-1e43-4c0d-9b32-e356159b4d5d" = false

# four of a kind beats a full house
# this test may not be in the suite but has not been intentionally rejected
# "d61e9e99-883b-4f99-b021-18f0ae50c5f4" = false

# both hands have four of a kind, tie goes to high quad
# this test may not be in the suite but has not been intentionally rejected
# "2e1c8c63-e0cb-4214-a01b-91954490d2fe" = false

# with multiple decks, both hands with identical four of a kind, tie determined by kicker
# this test may not be in the suite but has not been intentionally rejected
# "892ca75d-5474-495d-9f64-a6ce2dcdb7e1" = false

# straight flush beats four of a kind
# this test may not be in the suite but has not been intentionally rejected
# "923bd910-dc7b-4f7d-a330-8b42ec10a3ac" = false

# both hands have straight flush, tie goes to highest-ranked card
# this test may not be in the suite but has not been intentionally rejected
# "d0927f70-5aec-43db-aed8-1cbd1b6ee9ad" = false
