name: Tools

on:
  push:
    branches: [main]
    paths:
      - .github/labels.yml
      - .github/workflows/sync-labels.yml
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch:

jobs:
  sync-labels:
    name: Sync labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97
      - uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
